name: UpdateVersionNumbers

on:
  push:
    branches:
      - 'versioningWorkflow'
    tags-ignore:
      - '*.*'

jobs:
  updateVersionNumbers:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@v2
      - name: Export Number
        run: |
            export KLOCK_VERSION_NUMBER=$(awk -F '=' '/version=/{print $2}' gradle.properties)
            echo "::set-env name=KLOCK_VERSION_NUMBER::KLOCK_VERSION_NUMBER"

      - name: Checkout Korlibs version repo
        uses: actions/checkout@v2
        with:
          repository: korlibs/korlibs-versions

      - name: Bump version number
        run: |
          sed -i 's/klockVersion=.*/klockVersion='"$KLOCK_VERSION_NUMBER"'/g' versions.ver
          git config --global user.email korgeVersionBot@korge.org
          git config --global user.name korgeVersionBot
          git add versions.ver
          git commit -m "Bumped klock version number to $KLOCK_VERSION_NUMBER"

      - name: Create PR
        uses: peter-evans/create-pull-request@v2
        with:
          token: c316c7ae63bbc99a6b616d2e369949a6bf8c267e
